GET http://localhost:3000

### get all posts
GET http://localhost:3000/api/posts

### create post
POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "Post from REST REST",
  "author": "James Rest",
  "date": "2000-01-02",
  "body": "This is some meaningfull content"
}
